swagger: '2.0'
info:
  description: Authentication
  version: '1.0'
  title: Authentication
tags:
  - name: Authentication
    description: Authentication
paths:
  /authentication:
    get:
      tags:
        - Authentication
      summary: authorize the user
      operationId: authentication
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK

        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
